// Default prompt text for the deep-analysis pipeline: the opt-in pass over an
// uploaded source file that looks at frames, audio and the retention curve
// together. See lib/prompts/defaults/light-analysis.ts for how these defaults
// relate to admin overrides.
//
// COPY GUARDRAIL: no em or en dashes (U+2014 / U+2013) in prompt text.

export const SNAPSHOT_ANALYSIS_PROMPT = [
  "You describe frames from one window of a YouTube video, in chunkIndex order (0 is earliest). Most frames are placed in flanking pairs just before and just after a detected hard cut or transition, so consecutive chunks often straddle a real edit rather than an arbitrary moment; a window with no detected cuts instead gets evenly spaced frames across it.",
  "Each chunk is also given ocrText: text already recognized from that exact frame by a separate deterministic OCR pass (null if none was found). Treat it as ground truth, not a guess to verify. Do not re-transcribe or second-guess it, but you may reference it in notable_event/description when it's relevant to what changed (e.g. a caption or graphic appearing).",
  "For each chunk, classify: scene (best-fitting category), whether a face is visible, whether on-screen text/captions/graphics are present (contains_text, judge this visually even where ocrText is null, e.g. stylised or hard-to-read text), whether source code is visible, the amount of on-screen motion, how many distinct people are visible, and the camera's behaviour relative to the surrounding chunks.",
  "Also score these visual-packaging axes on the frame in isolation. shot_scale: how much of the frame the main subject occupies (close_up, medium, wide, or not_applicable when there is no clear subject such as a full-screen graphic). face_prominence: 0 when no face or a tiny one, 10 when a face dominates the frame (0 when no face). eye_contact: whether a visible subject looks into the lens. expression_intensity: 0 for a neutral or absent expression, 10 for an extreme one (0 when no face). color_contrast: 0 flat and muddy, 10 high-contrast and thumbstopping. visual_complexity: 0 clean and single-subject, 10 busy and crowded (a descriptor, neither end is better). text_prominence: 0 when there is no on-screen text or it is tiny, 10 when large text dominates the frame (score 0 whenever contains_text is false). brightness: dark, medium, or bright. Anchor every 0-10 axis at 0 absent, 5 moderately present, 10 as strong as it could plausibly be, and use the full range.",
  "Also give: notable_event (a single thing distinguishing this chunk from its neighbours, a cut, a zoom, a graphic appearing, a change of location, or null if nothing stands out), and a short free-text description of the composition and action.",
  "Base every judgment only on what's visible in that chunk's image (plus its given ocrText). Do not infer audio, speech, or viewer reaction.",
  "Return exactly one entry per supplied chunkIndex.",
  'Never output an em dash character (U+2014) anywhere in your response; if you would use one, rewrite the phrase with a comma, colon, parentheses, or two separate sentences instead.',
].join(" ")

export const AUDIO_ANALYSIS_PROMPT = [
  "You describe the non-verbal audio characteristics of one short clip from a YouTube video: delivery tone and energy, background music, distinct speaker count, and notable audible events.",
  "The spoken words are already transcribed elsewhere, and loudness/silence are measured separately. Do not transcribe speech, restate what is said, or estimate volume or silence here.",
  "Set music/music_description based only on audible background music, not speech. Estimate speakers as the number of distinct voices heard, not named identities.",
  "notable_events lists distinct audible occurrences worth flagging (laughter, a sudden volume or pace change, applause, a sound effect, an abrupt silence). Return an empty array if there's nothing notable.",
  // Audio-capable chat-completions models don't support response_format
  // json_schema or json_object (unlike the vision path above), so the shape
  // is enforced here in the prompt and re-checked by parseAudioAnalysis
  // instead - see callOpenAiChatCompletionsAudio for why no response_format
  // is sent at all.
  "Respond with only a single JSON object, no other text, with exactly these keys: music (boolean), music_description (string, or null when music is false), speakers (integer), tone (short string), energy (one of \"low\", \"moderate\", \"high\"), notable_events (array of strings, [] if none).",
  'Never output an em dash character (U+2014) in any string value you return; if you would use one, rewrite the phrase with a comma, colon, parentheses, or two separate sentences instead.',
].join(" ")

// Sent in the *user* turn alongside the audio itself, not just the developer
// turn above. Audio-capable chat models tend to treat the clip as something to
// converse with (replying "It sounds like you're describing..." to whatever is
// said) and ignore a developer-only instruction to emit JSON, so the task is
// re-anchored right next to the audio to make the model analyse it rather than
// answer it.
export const AUDIO_ANALYSIS_USER_PROMPT =
  "Analyse the non-verbal audio of the attached clip. Do not reply to, answer, or converse about anything said in it. Respond with only the single JSON object described, no prose before or after and no code fences."

// Blunter re-ask used for the one retry when the first response could not be
// parsed as the required JSON - see openAiRetentionWindowMediaAnalyzer.analyzeAudio.
export const AUDIO_ANALYSIS_RETRY_PROMPT =
  "Output ONLY the single JSON object with exactly the keys music, music_description, speakers, tone, energy, notable_events. No explanation, no prose, no code fences, no reply to the clip's contents. Analyse the attached audio and return that JSON object now."

export const TRANSCRIPT_TAXONOMY_PROMPT = [
  "You classify the SPOKEN TRANSCRIPT of one short window of a YouTube video into a fixed taxonomy. This is about what the words SAY and how they FEEL in this span alone, not how it is filmed or edited; use only the transcript, never infer visuals, music, editing or retention numbers. Classify only from what is genuinely said; never invent content that isn't there.",
  "Whoever is heard speaking may be the uploader, a co-host, a guest or a voiceover, so never pin what is said on a specific or gendered person (he, she, the creator); frame it as the uploader's own video.",
  "You are told the window's role (windowContext) only as background for what this span is doing; still score every field on the words in this span alone, never in comparison to any other window or video, and never think about view counts. Anchor every 0-10 scale: 0 the quality is absent, 5 moderately present, 10 as strong as it could plausibly be. Use the full range and be willing to give low scores.",
  "momentSummary: one sentence naming what is actually being said in this window.",
  "detail.content: substanceDensity (0 very little information in this span, 10 dense with ideas; judge ideas, not words); concreteness (0 abstract and vague, 10 concrete examples, numbers and names); novelty (0 familiar and well-worn, 10 fresh, contrarian or surprising); clarity (0 you cannot tell what is being said, 10 crystal clear).",
  "detail.emotion: dominantEmotion (excitement, curiosity, humor, awe, concern, outrage, warmth, calm, or neutral); energy (0 flat and low-key, 10 high intensity and enthusiasm); trajectory (how the energy moves across this span: steady, rising, falling, spike, or dip); vulnerability (0 impersonal, 10 candid vulnerable first-person disclosure).",
  "detail.rhetoric: narrativeVoice (first_person_story like 'I did X', second_person_guide like 'you should do X', third_person_report, or impersonal); directAddress (0 never addresses the viewer, 10 constantly talks to 'you'); persuasionDevices (the devices leaned on here: storytelling, data_evidence, authority, social_proof, analogy, contrast, urgency; report [\"none\"] when there are none); stakes (0 nothing at stake, 10 high vivid stakes or tension); posesQuestion (does the span pose a direct question to the viewer).",
  "detail.flow: topicShift (0 stays on one subject, 10 the subject clearly changes within this span); openLoopOpened (do the words open a curiosity loop or unresolved question here); openLoopResolved (do the words resolve or pay off a loop here); hasCta (does the span make an explicit call to action such as subscribe, comment, check the description, or a sponsor/ad read); fillerLevel (0 no filler, 10 heavy padding, throat-clearing and repeated points).",
  "detail.primaryEngagementDriver: the single main reason a viewer would keep watching this span (information, story, humor, personality, emotion, controversy, or utility).",
  "Never output an em dash character (U+2014) anywhere in your response; if you would use one, rewrite with a comma, colon, parentheses or two sentences instead.",
].join(" ")

export const EVENT_SYNTHESIS_PROMPT = [
  "You are given every piece of already-analysed evidence for one window of a YouTube video where audience retention rose, fell, or held steady: the window's retention delta, its transcript, deterministic editing metrics (cut count/rate, freeze/black-frame coverage), its average motion, a chronological list of already-described video frames (each with its own deterministic OCR text, ocrText, ground truth, not a guess), and an audio analysis of the clip. You are also given baseline: this video's own sparse full-video averages (cutsPerMinute, freeze/black coverage, speech rate, and motion), and baselineDeviation: where this window sits against each of those averages.",
  // Every other instruction here is written for a window whose retention moved,
  // and a hold is the one kind whose retention did not. Asked what drove the
  // change, told that unchanged evidence argues against an explanation, and told
  // to return nothing rather than pad, the synthesizer had exactly one
  // consistent answer for a hold: an empty events array. That is why the Holds
  // section arrived with an explanation from the transcript pass and nothing
  // else. Read on its own terms a hold is a positive result, often the longest
  // stretch on the page, and what it has to teach is what was holding.
  "kind tells you which window this is. When kind is 'hold', the retention finding is that the audience stayed: this stretch was detected precisely because the curve stayed flat across it, so its delta is near zero by construction and a near-zero delta is the result, never a reason to stay quiet. Do not look for what moved retention here, because nothing did. Identify instead what was sustaining attention across the span: a rhythm of cutting or motion the stretch keeps up, an energy level that holds rather than sagging, a visual or on-screen element that keeps giving the viewer something to read, an unresolved thread or a decision being worked through in the words. Confidence for a hold event is how strongly the evidence supports that this thing was present and plausibly kept viewers watching, not how strongly it moved a number.",
  "For a hold, the baseline and contrast comparisons change meaning as well. 'at' on a metric is a real finding rather than evidence against one, because it means the stretch sustained this video's own norm for its whole length instead of dipping below it, so say so plainly ('your cutting stays at about 11 per minute right through this stretch'). A metric that sits above the norm across a hold is the stronger finding still. Only a metric sitting below the norm across a hold is evidence against resting the event on it. The same goes for contrast: a target that matches its control across a long span is the stretch keeping something up, not the absence of a finding.",
  "Write each narrative to the uploader in the second person (you, your video), reviewing their own video. Whoever is heard speaking may be the uploader, a co-host, a guest, or a voiceover, so never pin what is said on a specific or gendered person (he, she, the creator, the host); frame it as the uploader's own video instead (say 'here you are still laying out the context', not 'he is still laying out the context').",
  "Identify the distinct, timestamped moments within the window that genuinely and non-obviously explain what the retention curve did there: a hard cut, a topic change in the transcript, a shift in pacing or energy, on-screen text or a graphic appearing/disappearing, a freeze or dead air, and so on. For a hold, where the curve did not move, the equivalent is the moment that best shows what the stretch was sustaining. A single window can have more than one, but do not manufacture one per cut: most cuts and most frames are unremarkable.",
  "Judge editing and pacing as deviations from the given baseline, not in absolute terms: a static, low-cut, low-energy stretch only explains a drop when it is slower or flatter than this video's own norm, and a burst of cuts or rising energy only explains a gain when it is livelier than the norm. Where a metric drives an event, reference the deviation in the narrative (for example 'your cuts fall to about 2 per minute here versus roughly 11 across the video').",
  "Do not work out those comparisons yourself. baselineDeviation gives you the direction already resolved for each metric (cutsPerMinute, freezeCoverage, blackCoverage, speechRate, motion), as 'below', 'at', 'above', or 'unavailable' when a number is missing. Treat it as authoritative and never contradict it. 'at' means this window matches the video's own norm on that metric, so it is evidence AGAINST an explanation resting on that metric: never call it a contrast, a deviation, unusual, or something that stands out, and do not cite the raw numbers as though they differ. In particular, when a metric sits near zero across the whole video (a video that barely cuts, or one that is static throughout), a window with no cuts or little motion is simply that video's normal and explains nothing on its own; look for a different cause, or return no event.",
  "Two motion figures are given and they are on different scales. motion and baseline.motion (and contrast's controlMotion/targetMotion) are numeric 0..1 frame-difference scores you may compare with each other; the motion field inside a visual frame's analysis is a categorical vision label for that single frame. Never compare a categorical frame label against a numeric baseline or describe it as above or below the video's usual motion. Judge motion against the norm only through baselineDeviation.motion or the contrast figures.",
  "For non-hook windows you are also given contrast: a target range covering the detected retention episode and the immediately preceding control range. It contains editing, deterministic audio, and deterministic visual-motion summaries for both ranges, target-minus-control deltas, and chunkIndex lists identifying which visual frames belong to each range. Motion is normalised 0..1 frame difference, so use it comparatively rather than assigning a universal good/bad threshold. Prefer this local comparison over a generic absolute judgment. Only attribute a change to editing, audio, speech rate, motion, or visuals when the target actually differs meaningfully from the control; unchanged evidence is evidence against that hypothesis. If the target has no sampled visual frame, audio coverage, or motion coverage, do not infer a change from missing data.",
  "You may also be given scriptExplanation: the transcript-only explanation the user has already been shown for this window. Your job is to add what the words alone cannot reveal. Only surface an event that ADDS a non-verbal cause (a cut, a freeze or dead air, an energy or pacing shift, a graphic appearing or disappearing) or that CONTRADICTS the script explanation. Never emit an event that merely restates scriptExplanation. When scriptExplanation is null, none has been generated yet, so surface the genuinely notable multimodal moments as usual.",
  "You may also be given transcriptTaxonomy: a structured read of this window's own spoken words (content density and concreteness, dominant emotion and energy and its trajectory, narrative voice and stakes, and flow signals such as topicShift, openLoopOpened/openLoopResolved and hasCta). Use it as corroborating context for what the words are doing, for example when a high topicShift or an energy dip lines up with a drop, or an opened loop lines up with a gain. It is a read of the transcript, not an independent modality, so never treat it as separate evidence from the transcript itself, and never surface an event on the taxonomy alone; the multimodal evidence still decides whether an event exists. It may be null when it has not been generated.",
  "You may also be given channelHistory: a compact summary of the retention events previously synthesized across this uploader's other deeply analysed videos, covering how many videos it draws on, which event types recur in their hooks, drop-offs, and gains (with how many distinct videos each recurs in), and a few example narratives. Treat it as prior context about what habitually moves retention on this channel: when the local evidence supports an event that matches a recurring channel pattern, note the recurrence in the narrative (for example 'a pattern that shows up across your other videos as well') and let the convergence nudge confidence up slightly. Never surface an event on channel history alone, and never let history suppress a well-evidenced local event that breaks the pattern; the local evidence always decides whether an event exists. channelHistory is null when too few other videos have been deeply analysed to establish a trend.",
  "For each event, give: event_type (the best-fitting category), timestamp_seconds (must fall within the window's fromSeconds/toSeconds), a one- or two-sentence narrative tying the evidence to what retention did across the window (its change, or its hold), primary_evidence (which evidence source most explains it; use 'combined' only when multiple sources genuinely converge on the same moment), and confidence (0..1: how strongly the supplied evidence supports both that this moment happened AND that it plausibly moved retention). Reserve confidence above 0.7 for moments where the evidence clearly converges, for example a hard cut plus an energy drop plus a matching retention step.",
  "Only surface events actually supported by the evidence given. Never invent frame content, transcript text, or audio characteristics that weren't provided. Prefer a few high-confidence, genuinely new events over many weak ones; if nothing clears a modest bar of being both well-supported and new, return an empty events array rather than padding.",
  'Never output an em dash character (U+2014) anywhere in your response; if you would use one, rewrite the phrase with a comma, colon, parentheses, or two separate sentences instead.',
].join(" ")
