-- Creator evaluation of the deep-analysis conclusion for one retention window.
-- One row is kept per user/window: changing a vote updates the existing row,
-- while the evaluated payload is snapshotted so offline evaluation still knows
-- exactly which model output the creator judged.
create table public.deep_analysis_insight_feedback (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  analysed_video_id uuid not null references public.analysed_videos(id) on delete cascade,
  retention_window_id uuid not null references public.retention_windows(id) on delete cascade,
  rating text not null check (rating in ('helpful', 'not_helpful')),
  reason text check (
    reason is null or reason in (
      'incorrect',
      'too_generic',
      'not_actionable',
      'already_known',
      'other'
    )
  ),
  notes text check (notes is null or char_length(notes) <= 1000),
  -- Immutable-at-vote-time evaluation context. This deliberately duplicates
  -- the event narratives and models: those rows can be regenerated by a deep
  -- analysis retry, but the feedback must remain attributable to what was
  -- actually visible when the creator voted.
  evaluated_payload jsonb not null default '{}'::jsonb,
  pipeline_version text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, retention_window_id)
);

create index deep_analysis_insight_feedback_video_idx
  on public.deep_analysis_insight_feedback (user_id, analysed_video_id);

alter table public.deep_analysis_insight_feedback enable row level security;

-- New Supabase projects may no longer expose public-schema tables to the Data
-- API automatically. Grant only the operations this feature uses; RLS below
-- still limits every operation to the signed-in creator's own rows.
grant select, insert, update
  on public.deep_analysis_insight_feedback to authenticated;

-- The application uses the signed-in user's Supabase client for reads and
-- writes. In addition to checking user_id, every mutation verifies that the
-- referenced video and window are both owned by that same user, preventing a
-- forged cross-user foreign-key reference.
create policy "Creators can read their own deep insight feedback"
  on public.deep_analysis_insight_feedback for select
  to authenticated
  using ((select auth.uid()) = user_id);

create policy "Creators can create feedback for their own windows"
  on public.deep_analysis_insight_feedback for insert
  to authenticated
  with check (
    (select auth.uid()) = user_id
    and exists (
      select 1
      from public.retention_windows rw
      where rw.id = retention_window_id
        and rw.user_id = (select auth.uid())
        and rw.analysed_video_id = analysed_video_id
    )
  );

create policy "Creators can update feedback for their own windows"
  on public.deep_analysis_insight_feedback for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check (
    (select auth.uid()) = user_id
    and exists (
      select 1
      from public.retention_windows rw
      where rw.id = retention_window_id
        and rw.user_id = (select auth.uid())
        and rw.analysed_video_id = analysed_video_id
    )
  );
