-- Full-video transcript pacing analysis generated by GPT. The payload contains
-- the 0-30 second hook window, subsequent 60 second windows, deterministic
-- speaking-rate metrics, and narrative pacing judgments.
alter table public.analysed_videos
  add column if not exists pacing_analysis jsonb;
